spring.application.name=ConfigServer

server.port=8888

spring.cloud.config.server.git.uri=https://github.com/zhen3100/AstonHomeworks
spring.cloud.config.server.git.default-label=main
spring.cloud.config.server.git.clone-on-start=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Logging
logging.level.org.springframework.cloud.config=DEBUG